/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:f7d0ac95-3647-4e55-b489-b8979a15df9c",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_FptPgNxIM",
    "aws_user_pools_web_client_id": "79bj5pquloulbbalndh1arhdta",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "eu-central-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Summaries",
            "region": "eu-central-1"
        },
        {
            "tableName": "Notes",
            "region": "eu-central-1"
        }
    ]
};


export default awsmobile;
